package main

import (
	"fmt"
	"strconv"
	"strings"
)

// Only validated numbers and generated frame names enter executable theme code.
func scriptTheme(entry spinnerEntry, background string, spinner, logo position) (string, string) {
	rgb, _ := strconv.ParseUint(strings.TrimPrefix(background, "#"), 16, 32)
	textColor := 1
	if float64(rgb>>16&255)*0.299+float64(rgb>>8&255)*0.587+float64(rgb&255)*0.114 > 150 {
		textColor = 0
	}
	var s strings.Builder
	fmt.Fprintf(&s, `# Generated by Plymouth Logo. Timing comes from the spinner's item.json.
Window.SetBackgroundTopColor(%.8f, %.8f, %.8f);
Window.SetBackgroundBottomColor(%.8f, %.8f, %.8f);
Plymouth.SetRefreshRate(60);
logo_image = Image("watermark.png");
logo_sprite = Sprite(logo_image);
`, float64(rgb>>16&255)/255, float64(rgb>>8&255)/255, float64(rgb&255)/255, float64(rgb>>16&255)/255, float64(rgb>>8&255)/255, float64(rgb&255)/255)
	for i := 0; i < entry.Frames; i++ {
		fmt.Fprintf(&s, "frames[%d] = Image(\"throbber-%04d.png\");\n", i, i+1)
	}
	fmt.Fprintf(&s, `text_color = %d;
spinner_sprite = Sprite(frames[0]);
frame = 0;
phase = 0;
dialog_active = 0;
prompt_sprite = Sprite();
entry_sprite = Sprite();
message_sprite = Sprite();
fun layout() {
 logo_sprite.SetPosition(Window.GetX() + (Window.GetWidth() - logo_image.GetWidth()) * %.6f,
                         Window.GetY() + (Window.GetHeight() - logo_image.GetHeight()) * %.6f, 1);
 spinner_sprite.SetPosition(Window.GetX() + (Window.GetWidth() - frames[0].GetWidth()) * %.6f,
                            Window.GetY() + (Window.GetHeight() - frames[0].GetHeight()) * %.6f, 2);
}
fun refresh() {
 layout();
 if (!global.dialog_active) {
  global.phase = (global.phase + %.10f / 60) %% %d;
  global.frame = Math.Int(global.phase);
  spinner_sprite.SetImage(frames[global.frame]);
 }
}
fun normal() {
 global.dialog_active = 0;
 prompt_sprite.SetOpacity(0);
 entry_sprite.SetOpacity(0);
 logo_sprite.SetOpacity(1);
 spinner_sprite.SetOpacity(1);
}
fun show_dialog(prompt, text) {
 global.dialog_active = 1;
 logo_sprite.SetOpacity(0);
 spinner_sprite.SetOpacity(0);
 local.prompt_image = Image.Text(prompt, text_color, text_color, text_color);
 local.entry_image = Image.Text(text, text_color, text_color, text_color);
 prompt_sprite.SetImage(prompt_image);
 entry_sprite.SetImage(entry_image);
 prompt_sprite.SetPosition(Window.GetX() + (Window.GetWidth()-prompt_image.GetWidth())/2,
                           Window.GetY() + Window.GetHeight()/2 - prompt_image.GetHeight() - 12, 100);
 entry_sprite.SetPosition(Window.GetX() + (Window.GetWidth()-entry_image.GetWidth())/2,
                          Window.GetY() + Window.GetHeight()/2 + 12, 100);
 prompt_sprite.SetOpacity(1);
 entry_sprite.SetOpacity(1);
}
fun password(prompt, bullets) {
 local.mask = "";
 for (local.i = 0; i < bullets && i < 128; i++) mask += "*";
 show_dialog(prompt, mask);
}
fun question(prompt, text) { show_dialog(prompt, text); }
fun message(text) {
 local.picture = Image.Text(text, text_color, text_color, text_color);
 message_sprite.SetImage(picture);
 message_sprite.SetPosition(Window.GetX() + (Window.GetWidth()-picture.GetWidth())/2,
                            Window.GetY() + Window.GetHeight() - picture.GetHeight() - 24, 100);
 message_sprite.SetOpacity(1);
}
fun system_update(progress) { message("Installing updates: " + Math.Int(progress) + "%%. Please keep power connected."); }
fun hide_message(text) { message_sprite.SetOpacity(0); }
fun quit() { Plymouth.SetRefreshFunction(NULL); }
layout();
normal();
Plymouth.SetRefreshFunction(refresh);
Plymouth.SetDisplayNormalFunction(normal);
Plymouth.SetDisplayPasswordFunction(password);
Plymouth.SetDisplayQuestionFunction(question);
Plymouth.SetDisplayMessageFunction(message);
Plymouth.SetHideMessageFunction(hide_message);
Plymouth.SetQuitFunction(quit);
Plymouth.SetSystemUpdateFunction(system_update);
`, textColor, logo.X/100, logo.Y/100, spinner.X/100, spinner.Y/100, entry.FPS, entry.Frames)
	conf := fmt.Sprintf(`[Plymouth Theme]
Name=OPi custom logo
Description=Configurable logo and frame animation
ModuleName=script

[script]
ImageDir=%s
ScriptFile=%s/opi-custom-logo.script

[opi-logo]
HorizontalAlignment=%.4f
VerticalAlignment=%.4f
WatermarkHorizontalAlignment=%.4f
WatermarkVerticalAlignment=%.4f
BackgroundStartColor=0x%s
AnimationFPS=%.8f
AnimationFrames=%d
`, themeDir, themeDir, spinner.X/100, spinner.Y/100, logo.X/100, logo.Y/100, strings.TrimPrefix(background, "#"), entry.FPS, entry.Frames)
	return conf, s.String()
}

const customThemeHook = `#!/bin/sh
set -eu
case "${1:-}" in prereqs) exit 0;; esac
. /usr/share/initramfs-tools/hook-functions
mkdir -p "$DESTDIR/usr/share/plymouth/themes"
cp -a /usr/share/plymouth/themes/opi-custom-logo "$DESTDIR/usr/share/plymouth/themes/"
PLUGIN_PATH="$(plymouth --get-splash-plugin-path)"
# The distribution hook follows alternatives, which may still select bgrt.
# Explicitly include our selected plugin and its shared-library dependencies.
MODULE="$(sed -n 's/^ModuleName=//p' /usr/share/plymouth/themes/opi-custom-logo/opi-custom-logo.plymouth)"
case "$MODULE" in script|two-step) ;; *) exit 1;; esac
copy_exec "$PLUGIN_PATH/$MODULE.so"
copy_exec "$PLUGIN_PATH/label.so"
`
