package main

import (
	"fmt"
	"strconv"
	"strings"
)

// Legacy requests keep their frame paths; new lists use a separate directory per layer.
func scriptTheme(entry spinnerEntry, background string, spinner, logo position) (string, string) {
	layers := []animationLayer{{animationSpec: animationSpec{Position: spinner, FPS: entry.FPS}, Frames: entry.Frames}}
	return renderScriptTheme(layers, []string{""}, background, logo)
}
func multiScriptTheme(layers []animationLayer, background string, logo position) (string, string) {
	prefixes := make([]string, len(layers))
	for i := range layers {
		prefixes[i] = fmt.Sprintf("animations/layer-%02d/", i)
	}
	return renderScriptTheme(layers, prefixes, background, logo)
}
func renderScriptTheme(layers []animationLayer, prefixes []string, background string, logo position) (string, string) {
	return renderScriptThemeWithLogo(layers, prefixes, background, logo, true)
}
func renderScriptThemeWithLogo(layers []animationLayer, prefixes []string, background string, logo position, showLogo bool) (string, string) {
	rgb, _ := strconv.ParseUint(strings.TrimPrefix(background, "#"), 16, 32)
	textColor := 1
	if float64(rgb>>16&255)*0.299+float64(rgb>>8&255)*0.587+float64(rgb&255)*0.114 > 150 {
		textColor = 0
	}
	var s strings.Builder
	fmt.Fprintf(&s, `# Generated by Plymouth Logo. Each layer has independent timing and position.
Window.SetBackgroundTopColor(%.8f, %.8f, %.8f);
Window.SetBackgroundBottomColor(%.8f, %.8f, %.8f);
Plymouth.SetRefreshRate(60);
logo_sprite = Sprite();
text_color = %d;
dialog_active = 0;
prompt_sprite = Sprite();
entry_sprite = Sprite();
message_sprite = Sprite();
`, float64(rgb>>16&255)/255, float64(rgb>>8&255)/255, float64(rgb&255)/255, float64(rgb>>16&255)/255, float64(rgb>>8&255)/255, float64(rgb&255)/255, textColor)
	if showLogo {
		s.WriteString("logo_image = Image(\"watermark.png\");\nlogo_sprite.SetImage(logo_image);\n")
	}
	for i, layer := range layers {
		for f := 0; f < layer.Frames; f++ {
			fmt.Fprintf(&s, "frames_%d[%d] = Image(\"%sthrobber-%04d.png\");\n", i, f, prefixes[i], f+1)
		}
		fmt.Fprintf(&s, "sprite_%d = Sprite(frames_%d[0]);\nphase_%d = 0;\n", i, i, i)
	}
	s.WriteString("fun layout() {\n")
	if showLogo {
		fmt.Fprintf(&s, ` logo_sprite.SetPosition(Window.GetX() + (Window.GetWidth() - logo_image.GetWidth()) * %.6f,
                         Window.GetY() + (Window.GetHeight() - logo_image.GetHeight()) * %.6f, 1);
`, logo.X/100, logo.Y/100)
	}
	for i, layer := range layers {
		if layer.Center {
			fmt.Fprintf(&s, " sprite_%d.SetPosition(Window.GetX() + Window.GetWidth() * %.6f - frames_%d[0].GetWidth()/2, Window.GetY() + Window.GetHeight() * %.6f - frames_%d[0].GetHeight()/2, %d);\n", i, layer.Position.X/100, i, layer.Position.Y/100, i, i+2)
		} else {
			fmt.Fprintf(&s, " sprite_%d.SetPosition(Window.GetX() + (Window.GetWidth() - frames_%d[0].GetWidth()) * %.6f, Window.GetY() + (Window.GetHeight() - frames_%d[0].GetHeight()) * %.6f, %d);\n", i, i, layer.Position.X/100, i, layer.Position.Y/100, i+2)
		}
	}
	s.WriteString("}\nfun refresh() {\n layout();\n if (!global.dialog_active) {\n")
	for i, layer := range layers {
		if layer.Frames == 1 {
			continue
		}
		fmt.Fprintf(&s, "  global.phase_%d = (global.phase_%d + %.10f / 60) %% %d;\n  sprite_%d.SetImage(frames_%d[Math.Int(global.phase_%d)]);\n", i, i, layer.FPS, layer.Frames, i, i, i)
	}
	s.WriteString(" }\n}\nfun normal() {\n global.dialog_active = 0;\n prompt_sprite.SetOpacity(0);\n entry_sprite.SetOpacity(0);\n logo_sprite.SetOpacity(1);\n")
	for i := range layers {
		fmt.Fprintf(&s, " sprite_%d.SetOpacity(1);\n", i)
	}
	s.WriteString("}\nfun show_dialog(prompt, text) {\n global.dialog_active = 1;\n logo_sprite.SetOpacity(0);\n")
	for i := range layers {
		fmt.Fprintf(&s, " sprite_%d.SetOpacity(0);\n", i)
	}
	s.WriteString(` local.prompt_image = Image.Text(prompt, text_color, text_color, text_color);
 local.entry_image = Image.Text(text, text_color, text_color, text_color);
 prompt_sprite.SetImage(prompt_image);
 entry_sprite.SetImage(entry_image);
 prompt_sprite.SetPosition(Window.GetX() + (Window.GetWidth()-prompt_image.GetWidth())/2,
                           Window.GetY() + Window.GetHeight()/2 - prompt_image.GetHeight() - 12, 100);
 entry_sprite.SetPosition(Window.GetX() + (Window.GetWidth()-entry_image.GetWidth())/2,
                          Window.GetY() + Window.GetHeight()/2 + 12, 100);
 prompt_sprite.SetOpacity(1);
 entry_sprite.SetOpacity(1);
}
fun password(prompt, bullets) {
 local.mask = "";
 for (local.i = 0; i < bullets && i < 128; i++) mask += "*";
 show_dialog(prompt, mask);
}
fun question(prompt, text) { show_dialog(prompt, text); }
fun message(text) {
 local.picture = Image.Text(text, text_color, text_color, text_color);
 message_sprite.SetImage(picture);
 message_sprite.SetPosition(Window.GetX() + (Window.GetWidth()-picture.GetWidth())/2,
                            Window.GetY() + Window.GetHeight() - picture.GetHeight() - 24, 100);
 message_sprite.SetOpacity(1);
}
fun system_update(progress) { message("Installing updates: " + Math.Int(progress) + "%. Please keep power connected."); }
fun hide_message(text) { message_sprite.SetOpacity(0); }
fun quit() { Plymouth.SetRefreshFunction(NULL); }
layout();
normal();
Plymouth.SetRefreshFunction(refresh);
Plymouth.SetDisplayNormalFunction(normal);
Plymouth.SetDisplayPasswordFunction(password);
Plymouth.SetDisplayQuestionFunction(question);
Plymouth.SetDisplayMessageFunction(message);
Plymouth.SetHideMessageFunction(hide_message);
Plymouth.SetQuitFunction(quit);
Plymouth.SetSystemUpdateFunction(system_update);
`)
	first := animationLayer{animationSpec: animationSpec{Position: position{50, 70}}}
	if len(layers) > 0 {
		first = layers[0]
	}
	conf := fmt.Sprintf(`[Plymouth Theme]
Name=OPi custom logo
Description=Configurable logo and independent animations
ModuleName=script

[script]
ImageDir=%s
ScriptFile=%s/opi-custom-logo.script

[opi-logo]
HorizontalAlignment=%.4f
VerticalAlignment=%.4f
WatermarkHorizontalAlignment=%.4f
WatermarkVerticalAlignment=%.4f
BackgroundStartColor=0x%s
AnimationFPS=%.8f
AnimationFrames=%d
`, themeDir, themeDir, first.Position.X/100, first.Position.Y/100, logo.X/100, logo.Y/100, strings.TrimPrefix(background, "#"), first.FPS, first.Frames)
	return conf, s.String()
}

const customThemeHook = `#!/bin/sh
set -eu
case "${1:-}" in prereqs) exit 0;; esac
. /usr/share/initramfs-tools/hook-functions
mkdir -p "$DESTDIR/usr/share/plymouth/themes"
cp -a /usr/share/plymouth/themes/opi-custom-logo "$DESTDIR/usr/share/plymouth/themes/"
# Originals are retained for editing/backup, not needed in the boot image.
rm -rf "$DESTDIR/usr/share/plymouth/themes/opi-custom-logo/sources"
PLUGIN_PATH="$(plymouth --get-splash-plugin-path)"
# The distribution hook follows alternatives, which may still select bgrt.
# Explicitly include our selected plugin and its shared-library dependencies.
MODULE="$(sed -n 's/^ModuleName=//p' /usr/share/plymouth/themes/opi-custom-logo/opi-custom-logo.plymouth)"
case "$MODULE" in script|two-step) ;; *) exit 1;; esac
copy_exec "$PLUGIN_PATH/$MODULE.so"
copy_exec "$PLUGIN_PATH/label.so"
`
