const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const elements=new Map();
const el=id=>{if(!elements.has(id))elements.set(id,{style:{},dataset:{},value:'320',naturalWidth:320,naturalHeight:320,files:[],getAttribute(name){return this[name];}});return elements.get(id);};
let source=1;
const ctx=vm.createContext({document:{getElementById:el,documentElement:{lang:'ko'},querySelectorAll(){return []}},navigator:{language:'ko'},location:{hash:'#test'},sessionStorage:{getItem(){},setItem(){}},history:{replaceState(){}},URL:{createObjectURL(){return 'blob:'+source++;},revokeObjectURL(){}},fetch:()=>new Promise(()=>{}),setTimeout(){},confirm:()=>true,FileReader:class{readAsDataURL(){this.result='data:image/png;base64,system';this.onload();}}});
vm.runInContext(fs.readFileSync('web/i18n.js','utf8'),ctx);
vm.runInContext(fs.readFileSync('web/app.js','utf8'),ctx);
(async()=>{
 await vm.runInContext(`
 let serverState={prepared:true,revision:1,size:320,applied:true,busy:false,ok:true};
 api=async(path)=>({json:async()=>serverState,blob:async()=>({})});
 poll();`,ctx);
 assert.equal(vm.runInContext('revision',ctx),1);
 await vm.runInContext(`
 $('size').value='480'; $('size').oninput(); data='chosen-image';showImage({});
 poll();`,ctx);
 assert.equal(vm.runInContext('revision',ctx),1,'displaying a draft must not reset revision');
 assert.equal(el('size').value,'480');
 assert.equal(vm.runInContext('data',ctx),'chosen-image');
 vm.runInContext("$('spinnerX').value='25';$('spinnerY').value='85';$('spinnerY').oninput();",ctx);
 vm.runInContext("background='#101827';presetGeneration=9;",ctx);
 const draft=el('logo').src;
 await vm.runInContext('serverState={...serverState,revision:2,size:128};poll();',ctx);
 assert.equal(el('size').value,'480','current-state refresh must not overwrite draft size');
 assert.equal(el('logo').src,draft,'current-state refresh must not overwrite draft image');
 assert.equal(vm.runInContext('data',ctx),'chosen-image');
 assert.equal(el('currentSize').textContent,'128 px');
 assert.equal(vm.runInContext('background',ctx),'#101827');
 assert.equal(vm.runInContext('presetGeneration',ctx),9);
 assert.equal(el('draftSpinner').style.top,'85%');
 assert.equal(el('draftSpinner').style.left,'25%');
 vm.runInContext("$('backgroundHex').value='#AABBCC';$('backgroundHex').oninput();",ctx);
 assert.equal(vm.runInContext('background',ctx),'#aabbcc');
 assert.equal(el('backgroundColor').value,'#aabbcc');
 assert.equal(el('draftScreen').style.backgroundColor,'#aabbcc');
 vm.runInContext("$('backgroundHex').value='#12';$('backgroundHex').oninput();",ctx);
 assert.equal(el('apply').disabled,true);
 assert.equal(vm.runInContext('background',ctx),'#aabbcc');
 await vm.runInContext('serverState={...serverState,revision:3,background:"#000000"};poll();',ctx);
 assert.equal(el('backgroundHex').value,'#12','poll must preserve partial HEX edits');
 vm.runInContext("$('backgroundColor').value='#102030';$('backgroundColor').oninput();",ctx);
 assert.equal(el('backgroundHex').value,'#102030');
 assert.equal(el('apply').disabled,false);
 vm.runInContext("$('spinnerItem').value='speaki';$('spinnerItem').onchange();",ctx);
 assert.equal(el('draftAnimation').src,'/spinner/speaki.png');
 await vm.runInContext('serverState={...serverState,revision:4,spinner_item:"pepe"};poll();',ctx);
 assert.equal(el('currentAnimation').src,'/installed-spinner.png?v=4');
 vm.runInContext("$('spinnerSize').value='240';$('spinnerSize').oninput();",ctx);
 assert.equal(el('draftAnimation').style.width,'12.5%');
 await vm.runInContext('serverState={...serverState,revision:5,spinner_size:64};poll();',ctx);
 assert.equal(el('spinnerSize').value,'240');
 assert.equal(el('draftAnimation').style.width,'12.5%');
 vm.runInContext("$('logoX').value='20';$('logoY').value='35';$('logoY').oninput();",ctx);
 await vm.runInContext('serverState={...serverState,revision:6,logo_position:{x:70,y:80}};poll();',ctx);
 assert.equal(el('logo').style.left,'20%');assert.equal(el('logo').style.top,'35%');
 assert.equal(el('currentLogo').style.left,'70%');assert.equal(el('currentLogo').style.top,'80%');
 vm.runInContext("applyLanguage('en');",ctx);
 assert.equal(ctx.document.documentElement.lang,'en');
 assert.equal(vm.runInContext("tr('로고 적용')",ctx),'Apply');
 assert.equal(vm.runInContext("tr('현재 적용된 로고')",ctx),'Applied logo');
 assert.equal(vm.runInContext('data',ctx),'chosen-image');
 assert.equal(el('size').value,'480','language switch must preserve draft size');
 assert.equal(el('spinnerSize').value,'240','language switch must preserve spinner size');
 assert.equal(el('logo').src,draft,'language switch must preserve chosen image');
 vm.runInContext("applyLanguage('ko');",ctx);
 assert.equal(vm.runInContext("tr('로고 적용')",ctx),'로고 적용');
 console.log('Editor regression checks passed: slider, draft image, and independent current-state refresh.');
})().catch(err=>{console.error(err);process.exitCode=1;});
